#!/bin/bash

set -e

export NODE_ENV=production;

# build wegit app
(
  cd ../apps/WeGit
  rm -rf ./dist
  npx parcel build --no-source-maps --no-content-hash index.jsx
  head -n 7 < index.jsx | cat - ./dist/index.js > ./dist/next.js && mv ./dist/next.js ./dist/index.js
)

#rm -rf .cache
rm -rf ./dist
# NOTE: build:appShell is needed for development
npm run build:appShell
# NOTE: build:appShell creates some dev file, remove it
rm ./dist/dev.*.js

parcel build --no-source-maps --no-content-hash entries/index.js

{
  head -n 1 < ./entries/index.html
  echo '<script>'
  cat ./dist/index.js
  echo '</script>'
} > ./dist/index.html
cp ./public/* dist
