#!/usr/bin/env node

// Imports
// =============================================================================

const fs = require('fs');
const net = require('net');
const git = require('isomorphic-git');
const gitInternals = require('isomorphic-git/dist/for-node/isomorphic-git/internal-apis');

const receiveInChunksMiddleware = require('wegit-lib/utils/receiveInChunksMiddleware');
const sendInChunksMiddleware = require('wegit-lib/utils/sendInChunksMiddleware');

const parser = require('./lib/parser');
const transportMiddleware = require('./lib/transportMiddleware');

// Utils
// =============================================================================

const findAgent = meshState => {
  const wgOsConnection = meshState.connections
    .filter(c => c.state === 'connected')
    .filter(c => c.user && c.user.type === 'browser')[0];
  if (!wgOsConnection) return;

  return wgOsConnection.user.id;
};

// Main
// =============================================================================

git.plugins.set('fs', fs);

const main = async () => {
  let meshState = {
    connections: [],
    globalState: 'disconnected',
  };

  const onChange = nextMeshState => (meshState = nextMeshState);

  const connection = net.connect({ port: 9001 }, () => {
    const remote = process.argv[2];
    const url = process.argv[3];
    const { send, onMessage } = receiveInChunksMiddleware(
      transportMiddleware({
        git,
        gitInternals,
        fs,
        remote,
        url,
      })(
        sendInChunksMiddleware({
          send(userId, message) {
            if (!userId) return;
            const { type, payload } = message;
            connection.write(
              JSON.stringify({
                method: 'send',
                args: [userId, { type: `app:${type}`, payload }],
              }),
            );
          },

          onMessage(message) {
            const value = parser.messageToStdout(message);
            console.warn('[<-]', value);

            process.stdout.write(value);
          },
        }),
      ),
    );
    connection.on('data', data => {
      const { method, args } = JSON.parse(data.toString());
      switch (method) {
        case 'change':
          return onChange(...args);
        case 'onMessage':
          return onMessage(...args);
        default:
          throw new Error('unknown method');
      }
    });

    process.stdin.setEncoding('utf8');
    process.stdin.on('readable', async () => {
      const value = process.stdin.read();

      if (value === null || value === '\n') {
        process.exit();
        return;
      }

      console.warn('[->]', value);
      const message = parser.stdinToMessage(value);
      send(findAgent(meshState), message);
    });
  });

  connection.on('end', () => console.warn('disconnected from server'));
};

main();
